language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
addons:
  apt:
    packages:
      - diffstat
sudo: false
before_script: cd $TRAVIS_BUILD_DIR/tests
script: python suite.py
before_deploy:
  - cd $TRAVIS_BUILD_DIR/
  - rm -rf $TRAVIS_BUILD_DIR/dist/*
deploy:
  provider: pypi
  user: suse
  password:
    secure: R4+YNPW2tsiY06hibGvONYn0//1z1QdcY8VmNbYpIRly4eTAbPE9uejKpyuflUkznpEkoqCdFzi5FNFhgat9N+AkIKyX9NTkf0oxaKKbdqBM7H1V8bqLYlAO479262spRyO0ee5fV5v6g81AFjncIV+pGjtQ0Vg/sjVcvGa61bs=
  on:
    tags: true
    distributions: sdist
    repo: openSUSE/osc
